
 [development]
 address = "localhost"
 port = 8001
 keep_alive = 0
 log = "normal"
 limits = { forms = 32768 }



 [staging]

 address = "0.0.0.0"
 port = 8001
 keep_alive = 0
 log = "normal"
 limits = { forms = 32768 }



 [production]

 address = "0.0.0.0"
 port = 8001
 keep_alive = 0
 log = "critical"
 limits = { forms = 32768 }


 